---
title: Poverty Analysis using ASEC-CPS 2018
author: "Fernando Rios-Avila"
format: 
  html: 
    code-fold: true
    echo: true
    output: false
    keep-ipynb: true
jupyter: nbstata
---

## Setup

For the following analysis, all the data process is done in the file [`example.do`](example.do).

This do-file loads the data and creates auxiliary variables that mimic the interval censoring of the data (in this case household income). We use the brackets of income that are generally used for collecting Family income data in the monthly CPS.

Because household income is not likely to follow a conditional normal distribution, we use the log of household income percapita as the variable to be imputed. We recover the original scale of the data after imputation.

Using the brackets data, it estimates the heteroskedastic interval regression model, and then uses the `intreg_mi` command to obtain the imputations for the data. 

The imputed data is then used to estimate Poverty Status across selected groups, using the fully observed data, and the imputed data.

```stata
run example.do
```

## Model Specification

For imputation we assume `official total income` are a function of household demographics including # adults, # working adults, # children, # of ppl with higher education, #region, House ownership.

For modeling, we only the estimation of poverty headcounts by different groups groups

### Poverty head count by Family Race

|                      | Fully Observed |      Imputed |
| -------------------- | :----------: | :----------: |
| White HH             |        7.351 |        7.315 |
|                      |      (0.150) |      (0.153) |
| Black HH             |        18.70 |        18.63 |
|                      |      (0.584) |      (0.586) |
| Hispanic HH          |        17.81 |        17.58 |
|                      |      (0.500) |      (0.515) |
| Other HH             |        10.67 |        10.51 |
|                      |      (0.563) |      (0.565) |
| Mixed Race HH        |        8.715 |        8.644 |
|                      |      (0.506) |      (0.518) |
| Observations         |        73614 |        73614 |

Household Race is defined based on the overall Composition of the family. For example, a household would be categorized as Black, if all members in the family identify as Black.

Mixed raced families are those with members from different race categories. 

### Poverty head count by Region


|                      | Fully Observed |      Imputed |
| -------------------- | :----------: | :----------: |
| new england division |        9.189 |        8.962 |
|                      |      (0.575) |      (0.556) |
| middle atlantic division |        10.10 |        10.04 |
|                      |      (0.441) |      (0.455) |
| east north central division |        10.20 |        10.14 |
|                      |      (0.407) |      (0.415) |
| west north central division |        9.601 |        9.469 |
|                      |      (0.512) |      (0.516) |
| south atlantic division |        10.78 |        10.70 |
|                      |      (0.341) |      (0.344) |
| east south central division |        11.97 |        11.93 |
|                      |      (0.523) |      (0.529) |
| west south central division |        12.32 |        12.18 |
|                      |      (0.452) |      (0.452) |
| mountain division    |        9.763 |        9.794 |
|                      |      (0.453) |      (0.489) |
| pacific division     |        9.976 |        9.889 |
|                      |      (0.357) |      (0.368) |
| Observations         |        73614 |        73614 |



### Poverty head count by Education Level


|                      | Fully Observed |      Imputed |
| -------------------- | :----------: | :----------: |
| 12th grade, no diploma |        37.31 |        37.40 |
|                      |      (0.986) |      (1.008) |
| high school diploma or equivalent |        17.73 |        17.63 |
|                      |      (0.395) |      (0.398) |
| some college but no degree |        12.82 |        12.80 |
|                      |      (0.386) |      (0.397) |
| associate's degree, occupational/vocational program |        7.978 |        8.019 |
|                      |      (0.557) |      (0.584) |
| associate's degree, academic program |        7.476 |        7.248 |
|                      |      (0.474) |      (0.468) |
| bachelor's degree    |        4.495 |        4.393 |
|                      |      (0.196) |      (0.198) |
| master's degree      |        3.125 |        2.981 |
|                      |      (0.218) |      (0.211) |
| professional school degree |        2.447 |        2.487 |
|                      |      (0.479) |      (0.481) |
| doctorate degree     |        1.632 |        1.628 |
|                      |      (0.298) |      (0.300) |
| Observations         |        73614 |        73614 |





The education is defined as the highest education level attained by any member within a family.

